<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\AnalystEstimate;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<AnalystEstimate>
 */
final readonly class AnalystEstimateMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|AnalystEstimate
	{
		$context = AnalystEstimate::createContext($context);

		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->nonEmptyString(),
			'revenueLow' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'revenueHigh' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'revenueAvg' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'ebitdaLow' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'ebitdaHigh' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'ebitdaAvg' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'ebitLow' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'ebitHigh' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'ebitAvg' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'netIncomeLow' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'netIncomeHigh' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'netIncomeAvg' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'sgaExpenseLow' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'sgaExpenseHigh' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'sgaExpenseAvg' => $ts->optional($ts->union([$ts->int(), $ts->float()])),
			'epsAvg' => $ts->optional($ts->float()),
			'epsHigh' => $ts->optional($ts->float()),
			'epsLow' => $ts->optional($ts->float()),
			'numAnalystsRevenue' => $ts->optional($ts->int()),
			'numAnalystsEps' => $ts->optional($ts->int()),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new AnalystEstimate(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(AnalystEstimate::class);
	}
}
