<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\AvailableExchange;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<AvailableExchange>
 */
final readonly class AvailableExchangeMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|AvailableExchange
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'exchange' => $ts->nonEmptyString(),
			'name' => $ts->nonEmptyString(),
			'countryName' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'countryCode' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'symbolSuffix' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'delay' => $ts->optional($ts->nullable($ts->nonEmptyString())),
		],
			identifier: 'exchange',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new AvailableExchange(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(AvailableExchange::class);
	}
}
