<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\AvailableExchange;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<AvailableExchange>
 */
final readonly class AvailableExchangeMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|AvailableExchange
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'exchange' => $ts->nonEmptyString(),
			'name' => $ts->nonEmptyString(),
			'countryName' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'countryCode' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'symbolSuffix' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'delay' => $ts->optional($ts->nullable($ts->nonEmptyString())),
		],
			identifier: 'exchange',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new AvailableExchange(...array_intersect_key($values, [
			'exchange' => true,
			'name' => true,
			'countryName' => true,
			'countryCode' => true,
			'symbolSuffix' => true,
			'delay' => true,
		]));
	}


	public function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(AvailableExchange::class);
	}
}
