<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Enum\Period;
use Shredio\FmpClient\Payload\BalanceSheetStatement;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<BalanceSheetStatement>
 */
final readonly class BalanceSheetStatementMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|BalanceSheetStatement
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->nonEmptyString(),
			'reportedCurrency' => $ts->string(),
			'cik' => $ts->string(),
			'filingDate' => $ts->string(),
			'acceptedDate' => $ts->string(),
			'fiscalYear' => $ts->string(),
			'period' => $ts->mapper(Period::class),
			'cashAndCashEquivalents' => $ts->optional($ts->float()),
			'shortTermInvestments' => $ts->optional($ts->float()),
			'cashAndShortTermInvestments' => $ts->optional($ts->float()),
			'netReceivables' => $ts->optional($ts->float()),
			'accountsReceivables' => $ts->optional($ts->float()),
			'otherReceivables' => $ts->optional($ts->float()),
			'inventory' => $ts->optional($ts->float()),
			'prepaids' => $ts->optional($ts->float()),
			'otherCurrentAssets' => $ts->optional($ts->float()),
			'totalCurrentAssets' => $ts->optional($ts->float()),
			'propertyPlantEquipmentNet' => $ts->optional($ts->float()),
			'goodwill' => $ts->optional($ts->float()),
			'intangibleAssets' => $ts->optional($ts->float()),
			'goodwillAndIntangibleAssets' => $ts->optional($ts->float()),
			'longTermInvestments' => $ts->optional($ts->float()),
			'taxAssets' => $ts->optional($ts->float()),
			'otherNonCurrentAssets' => $ts->optional($ts->float()),
			'totalNonCurrentAssets' => $ts->optional($ts->float()),
			'otherAssets' => $ts->optional($ts->float()),
			'totalAssets' => $ts->optional($ts->float()),
			'totalPayables' => $ts->optional($ts->float()),
			'accountPayables' => $ts->optional($ts->float()),
			'otherPayables' => $ts->optional($ts->float()),
			'accruedExpenses' => $ts->optional($ts->float()),
			'shortTermDebt' => $ts->optional($ts->float()),
			'capitalLeaseObligationsCurrent' => $ts->optional($ts->float()),
			'taxPayables' => $ts->optional($ts->float()),
			'deferredRevenue' => $ts->optional($ts->float()),
			'otherCurrentLiabilities' => $ts->optional($ts->float()),
			'totalCurrentLiabilities' => $ts->optional($ts->float()),
			'longTermDebt' => $ts->optional($ts->float()),
			'capitalLeaseObligationsNonCurrent' => $ts->optional($ts->float()),
			'deferredRevenueNonCurrent' => $ts->optional($ts->float()),
			'deferredTaxLiabilitiesNonCurrent' => $ts->optional($ts->float()),
			'otherNonCurrentLiabilities' => $ts->optional($ts->float()),
			'totalNonCurrentLiabilities' => $ts->optional($ts->float()),
			'otherLiabilities' => $ts->optional($ts->float()),
			'capitalLeaseObligations' => $ts->optional($ts->float()),
			'totalLiabilities' => $ts->optional($ts->float()),
			'treasuryStock' => $ts->optional($ts->float()),
			'preferredStock' => $ts->optional($ts->float()),
			'commonStock' => $ts->optional($ts->float()),
			'retainedEarnings' => $ts->optional($ts->float()),
			'additionalPaidInCapital' => $ts->optional($ts->float()),
			'accumulatedOtherComprehensiveIncomeLoss' => $ts->optional($ts->float()),
			'otherTotalStockholdersEquity' => $ts->optional($ts->float()),
			'totalStockholdersEquity' => $ts->optional($ts->float()),
			'totalEquity' => $ts->optional($ts->float()),
			'minorityInterest' => $ts->optional($ts->float()),
			'totalLiabilitiesAndTotalEquity' => $ts->optional($ts->float()),
			'totalInvestments' => $ts->optional($ts->float()),
			'totalDebt' => $ts->optional($ts->float()),
			'netDebt' => $ts->optional($ts->float()),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new BalanceSheetStatement(...array_intersect_key($values, [
			'symbol' => true,
			'date' => true,
			'reportedCurrency' => true,
			'cik' => true,
			'filingDate' => true,
			'acceptedDate' => true,
			'fiscalYear' => true,
			'period' => true,
			'cashAndCashEquivalents' => true,
			'shortTermInvestments' => true,
			'cashAndShortTermInvestments' => true,
			'netReceivables' => true,
			'accountsReceivables' => true,
			'otherReceivables' => true,
			'inventory' => true,
			'prepaids' => true,
			'otherCurrentAssets' => true,
			'totalCurrentAssets' => true,
			'propertyPlantEquipmentNet' => true,
			'goodwill' => true,
			'intangibleAssets' => true,
			'goodwillAndIntangibleAssets' => true,
			'longTermInvestments' => true,
			'taxAssets' => true,
			'otherNonCurrentAssets' => true,
			'totalNonCurrentAssets' => true,
			'otherAssets' => true,
			'totalAssets' => true,
			'totalPayables' => true,
			'accountPayables' => true,
			'otherPayables' => true,
			'accruedExpenses' => true,
			'shortTermDebt' => true,
			'capitalLeaseObligationsCurrent' => true,
			'taxPayables' => true,
			'deferredRevenue' => true,
			'otherCurrentLiabilities' => true,
			'totalCurrentLiabilities' => true,
			'longTermDebt' => true,
			'capitalLeaseObligationsNonCurrent' => true,
			'deferredRevenueNonCurrent' => true,
			'deferredTaxLiabilitiesNonCurrent' => true,
			'otherNonCurrentLiabilities' => true,
			'totalNonCurrentLiabilities' => true,
			'otherLiabilities' => true,
			'capitalLeaseObligations' => true,
			'totalLiabilities' => true,
			'treasuryStock' => true,
			'preferredStock' => true,
			'commonStock' => true,
			'retainedEarnings' => true,
			'additionalPaidInCapital' => true,
			'accumulatedOtherComprehensiveIncomeLoss' => true,
			'otherTotalStockholdersEquity' => true,
			'totalStockholdersEquity' => true,
			'totalEquity' => true,
			'minorityInterest' => true,
			'totalLiabilitiesAndTotalEquity' => true,
			'totalInvestments' => true,
			'totalDebt' => true,
			'netDebt' => true,
		]));
	}


	public function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(BalanceSheetStatement::class);
	}
}
