<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Enum\Period;
use Shredio\FmpClient\Payload\BalanceSheetStatementGrowth;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<BalanceSheetStatementGrowth>
 */
final readonly class BalanceSheetStatementGrowthMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|BalanceSheetStatementGrowth
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'date' => $ts->string(),
			'symbol' => $ts->nonEmptyString(),
			'calendarYear' => $ts->string(),
			'period' => $ts->mapper(Period::class),
			'growthCashAndCashEquivalents' => $ts->float(),
			'growthShortTermInvestments' => $ts->float(),
			'growthCashAndShortTermInvestments' => $ts->float(),
			'growthNetReceivables' => $ts->float(),
			'growthInventory' => $ts->float(),
			'growthOtherCurrentAssets' => $ts->float(),
			'growthTotalCurrentAssets' => $ts->float(),
			'growthPropertyPlantEquipmentNet' => $ts->float(),
			'growthGoodwill' => $ts->float(),
			'growthIntangibleAssets' => $ts->float(),
			'growthGoodwillAndIntangibleAssets' => $ts->float(),
			'growthLongTermInvestments' => $ts->float(),
			'growthTaxAssets' => $ts->float(),
			'growthOtherNonCurrentAssets' => $ts->float(),
			'growthTotalNonCurrentAssets' => $ts->float(),
			'growthOtherAssets' => $ts->float(),
			'growthTotalAssets' => $ts->float(),
			'growthAccountPayables' => $ts->float(),
			'growthShortTermDebt' => $ts->float(),
			'growthTaxPayables' => $ts->float(),
			'growthDeferredRevenue' => $ts->float(),
			'growthOtherCurrentLiabilities' => $ts->float(),
			'growthTotalCurrentLiabilities' => $ts->float(),
			'growthLongTermDebt' => $ts->float(),
			'growthDeferredRevenueNonCurrent' => $ts->float(),
			'growthDeferrredTaxLiabilitiesNonCurrent' => $ts->float(),
			'growthOtherNonCurrentLiabilities' => $ts->float(),
			'growthTotalNonCurrentLiabilities' => $ts->float(),
			'growthOtherLiabilities' => $ts->float(),
			'growthTotalLiabilities' => $ts->float(),
			'growthCommonStock' => $ts->float(),
			'growthRetainedEarnings' => $ts->float(),
			'growthAccumulatedOtherComprehensiveIncomeLoss' => $ts->float(),
			'growthOthertotalStockholdersEquity' => $ts->float(),
			'growthTotalStockholdersEquity' => $ts->float(),
			'growthTotalLiabilitiesAndStockholdersEquity' => $ts->float(),
			'growthTotalInvestments' => $ts->float(),
			'growthTotalDebt' => $ts->float(),
			'growthNetDebt' => $ts->float(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new BalanceSheetStatementGrowth(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(BalanceSheetStatementGrowth::class);
	}
}
