<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Enum\Period;
use Shredio\FmpClient\Payload\BalanceSheetStatementGrowthBulk;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<BalanceSheetStatementGrowthBulk>
 */
final readonly class BalanceSheetStatementGrowthBulkMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|BalanceSheetStatementGrowthBulk
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'calendarYear' => $ts->string(),
			'period' => $ts->mapper(Period::class),
			'growthCashAndCashEquivalents' => $ts->float(),
			'growthShortTermInvestments' => $ts->float(),
			'growthCashAndShortTermInvestments' => $ts->float(),
			'growthNetReceivables' => $ts->float(),
			'growthInventory' => $ts->float(),
			'growthOtherCurrentAssets' => $ts->float(),
			'growthTotalCurrentAssets' => $ts->float(),
			'growthPropertyPlantEquipmentNet' => $ts->float(),
			'growthGoodwill' => $ts->float(),
			'growthIntangibleAssets' => $ts->float(),
			'growthGoodwillAndIntangibleAssets' => $ts->float(),
			'growthLongTermInvestments' => $ts->float(),
			'growthTaxAssets' => $ts->float(),
			'growthOtherNonCurrentAssets' => $ts->float(),
			'growthTotalNonCurrentAssets' => $ts->float(),
			'growthOtherAssets' => $ts->float(),
			'growthTotalAssets' => $ts->float(),
			'growthAccountPayables' => $ts->float(),
			'growthShortTermDebt' => $ts->float(),
			'growthTaxPayables' => $ts->float(),
			'growthDeferredRevenue' => $ts->float(),
			'growthOtherCurrentLiabilities' => $ts->float(),
			'growthTotalCurrentLiabilities' => $ts->float(),
			'growthLongTermDebt' => $ts->float(),
			'growthDeferredRevenueNonCurrent' => $ts->float(),
			'growthDeferredTaxLiabilitiesNonCurrent' => $ts->float(),
			'growthOtherNonCurrentLiabilities' => $ts->float(),
			'growthTotalNonCurrentLiabilities' => $ts->float(),
			'growthOtherLiabilities' => $ts->float(),
			'growthTotalLiabilities' => $ts->float(),
			'growthCommonStock' => $ts->float(),
			'growthRetainedEarnings' => $ts->float(),
			'growthAccumulatedOtherComprehensiveIncomeLoss' => $ts->float(),
			'growthOthertotalStockholdersEquity' => $ts->float(),
			'growthTotalStockholdersEquity' => $ts->float(),
			'growthTotalLiabilitiesAndStockholdersEquity' => $ts->float(),
			'growthTotalInvestments' => $ts->float(),
			'growthTotalDebt' => $ts->float(),
			'growthNetDebt' => $ts->float(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new BalanceSheetStatementGrowthBulk(...array_intersect_key($values, [
			'symbol' => true,
			'date' => true,
			'calendarYear' => true,
			'period' => true,
			'growthCashAndCashEquivalents' => true,
			'growthShortTermInvestments' => true,
			'growthCashAndShortTermInvestments' => true,
			'growthNetReceivables' => true,
			'growthInventory' => true,
			'growthOtherCurrentAssets' => true,
			'growthTotalCurrentAssets' => true,
			'growthPropertyPlantEquipmentNet' => true,
			'growthGoodwill' => true,
			'growthIntangibleAssets' => true,
			'growthGoodwillAndIntangibleAssets' => true,
			'growthLongTermInvestments' => true,
			'growthTaxAssets' => true,
			'growthOtherNonCurrentAssets' => true,
			'growthTotalNonCurrentAssets' => true,
			'growthOtherAssets' => true,
			'growthTotalAssets' => true,
			'growthAccountPayables' => true,
			'growthShortTermDebt' => true,
			'growthTaxPayables' => true,
			'growthDeferredRevenue' => true,
			'growthOtherCurrentLiabilities' => true,
			'growthTotalCurrentLiabilities' => true,
			'growthLongTermDebt' => true,
			'growthDeferredRevenueNonCurrent' => true,
			'growthDeferredTaxLiabilitiesNonCurrent' => true,
			'growthOtherNonCurrentLiabilities' => true,
			'growthTotalNonCurrentLiabilities' => true,
			'growthOtherLiabilities' => true,
			'growthTotalLiabilities' => true,
			'growthCommonStock' => true,
			'growthRetainedEarnings' => true,
			'growthAccumulatedOtherComprehensiveIncomeLoss' => true,
			'growthOthertotalStockholdersEquity' => true,
			'growthTotalStockholdersEquity' => true,
			'growthTotalLiabilitiesAndStockholdersEquity' => true,
			'growthTotalInvestments' => true,
			'growthTotalDebt' => true,
			'growthNetDebt' => true,
		]));
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(BalanceSheetStatementGrowthBulk::class);
	}
}
