<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\BatchExchangeDetailedQuote;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<BatchExchangeDetailedQuote>
 */
final readonly class BatchExchangeDetailedQuoteMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|BatchExchangeDetailedQuote
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'name' => $ts->string(),
			'exchange' => $ts->string(),
			'price' => $ts->optional($ts->nullable($ts->float())),
			'changePercentage' => $ts->optional($ts->nullable($ts->float())),
			'change' => $ts->optional($ts->nullable($ts->float())),
			'volume' => $ts->optional($ts->nullable($ts->union([$ts->int(), $ts->float()]))),
			'dayLow' => $ts->optional($ts->nullable($ts->float())),
			'dayHigh' => $ts->optional($ts->nullable($ts->float())),
			'yearHigh' => $ts->optional($ts->nullable($ts->float())),
			'yearLow' => $ts->optional($ts->nullable($ts->float())),
			'marketCap' => $ts->optional($ts->nullable($ts->int())),
			'priceAvg50' => $ts->optional($ts->nullable($ts->float())),
			'priceAvg200' => $ts->optional($ts->nullable($ts->float())),
			'open' => $ts->optional($ts->nullable($ts->float())),
			'previousClose' => $ts->optional($ts->nullable($ts->float())),
			'timestamp' => $ts->optional($ts->nullable($ts->int())),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new BatchExchangeDetailedQuote(...array_intersect_key($values, [
			'symbol' => true,
			'name' => true,
			'exchange' => true,
			'price' => true,
			'changePercentage' => true,
			'change' => true,
			'volume' => true,
			'dayLow' => true,
			'dayHigh' => true,
			'yearHigh' => true,
			'yearLow' => true,
			'marketCap' => true,
			'priceAvg50' => true,
			'priceAvg200' => true,
			'open' => true,
			'previousClose' => true,
			'timestamp' => true,
		]));
	}


	public function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(BatchExchangeDetailedQuote::class);
	}
}
