<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Enum\Period;
use Shredio\FmpClient\Payload\CashFlowStatement;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<CashFlowStatement>
 */
final readonly class CashFlowStatementMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|CashFlowStatement
	{
		$context = CashFlowStatement::createContext($context);

		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'reportedCurrency' => $ts->string(),
			'cik' => $ts->string(),
			'filingDate' => $ts->string(),
			'acceptedDate' => $ts->string(),
			'fiscalYear' => $ts->string(),
			'period' => $ts->mapper(Period::class),
			'netIncome' => $ts->optional($ts->float()),
			'depreciationAndAmortization' => $ts->optional($ts->float()),
			'deferredIncomeTax' => $ts->optional($ts->float()),
			'stockBasedCompensation' => $ts->optional($ts->float()),
			'changeInWorkingCapital' => $ts->optional($ts->float()),
			'accountsReceivables' => $ts->optional($ts->float()),
			'inventory' => $ts->optional($ts->float()),
			'accountsPayables' => $ts->optional($ts->float()),
			'otherWorkingCapital' => $ts->optional($ts->float()),
			'otherNonCashItems' => $ts->optional($ts->float()),
			'netCashProvidedByOperatingActivities' => $ts->optional($ts->float()),
			'investmentsInPropertyPlantAndEquipment' => $ts->optional($ts->float()),
			'acquisitionsNet' => $ts->optional($ts->float()),
			'purchasesOfInvestments' => $ts->optional($ts->float()),
			'salesMaturitiesOfInvestments' => $ts->optional($ts->float()),
			'otherInvestingActivities' => $ts->optional($ts->float()),
			'netCashProvidedByInvestingActivities' => $ts->optional($ts->float()),
			'netDebtIssuance' => $ts->optional($ts->float()),
			'longTermNetDebtIssuance' => $ts->optional($ts->float()),
			'shortTermNetDebtIssuance' => $ts->optional($ts->float()),
			'netStockIssuance' => $ts->optional($ts->float()),
			'netCommonStockIssuance' => $ts->optional($ts->float()),
			'commonStockIssuance' => $ts->optional($ts->float()),
			'commonStockRepurchased' => $ts->optional($ts->float()),
			'netPreferredStockIssuance' => $ts->optional($ts->float()),
			'netDividendsPaid' => $ts->optional($ts->float()),
			'commonDividendsPaid' => $ts->optional($ts->float()),
			'preferredDividendsPaid' => $ts->optional($ts->float()),
			'otherFinancingActivities' => $ts->optional($ts->float()),
			'netCashProvidedByFinancingActivities' => $ts->optional($ts->float()),
			'effectOfForexChangesOnCash' => $ts->optional($ts->float()),
			'netChangeInCash' => $ts->optional($ts->float()),
			'cashAtEndOfPeriod' => $ts->optional($ts->float()),
			'cashAtBeginningOfPeriod' => $ts->optional($ts->float()),
			'operatingCashFlow' => $ts->optional($ts->float()),
			'capitalExpenditure' => $ts->optional($ts->float()),
			'freeCashFlow' => $ts->optional($ts->float()),
			'incomeTaxesPaid' => $ts->optional($ts->float()),
			'interestPaid' => $ts->optional($ts->float()),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new CashFlowStatement(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(CashFlowStatement::class);
	}
}
