<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Enum\Period;
use Shredio\FmpClient\Payload\CashFlowStatementGrowthBulk;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<CashFlowStatementGrowthBulk>
 */
final readonly class CashFlowStatementGrowthBulkMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|CashFlowStatementGrowthBulk
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'calendarYear' => $ts->string(),
			'period' => $ts->mapper(Period::class),
			'growthNetIncome' => $ts->float(),
			'growthDepreciationAndAmortization' => $ts->float(),
			'growthDeferredIncomeTax' => $ts->float(),
			'growthStockBasedCompensation' => $ts->float(),
			'growthChangeInWorkingCapital' => $ts->float(),
			'growthAccountsReceivables' => $ts->float(),
			'growthInventory' => $ts->float(),
			'growthAccountsPayables' => $ts->float(),
			'growthOtherWorkingCapital' => $ts->float(),
			'growthOtherNonCashItems' => $ts->float(),
			'growthNetCashProvidedByOperatingActivites' => $ts->float(),
			'growthInvestmentsInPropertyPlantAndEquipment' => $ts->float(),
			'growthAcquisitionsNet' => $ts->float(),
			'growthPurchasesOfInvestments' => $ts->float(),
			'growthSalesMaturitiesOfInvestments' => $ts->float(),
			'growthOtherInvestingActivites' => $ts->float(),
			'growthNetCashUsedForInvestingActivites' => $ts->float(),
			'growthDebtRepayment' => $ts->float(),
			'growthCommonStockIssued' => $ts->float(),
			'growthCommonStockRepurchased' => $ts->float(),
			'growthDividendsPaid' => $ts->float(),
			'growthOtherFinancingActivites' => $ts->float(),
			'growthNetCashUsedProvidedByFinancingActivities' => $ts->float(),
			'growthEffectOfForexChangesOnCash' => $ts->float(),
			'growthNetChangeInCash' => $ts->float(),
			'growthCashAtEndOfPeriod' => $ts->float(),
			'growthCashAtBeginningOfPeriod' => $ts->float(),
			'growthOperatingCashFlow' => $ts->float(),
			'growthCapitalExpenditure' => $ts->float(),
			'growthFreeCashFlow' => $ts->float(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new CashFlowStatementGrowthBulk(...array_intersect_key($values, [
			'symbol' => true,
			'date' => true,
			'calendarYear' => true,
			'period' => true,
			'growthNetIncome' => true,
			'growthDepreciationAndAmortization' => true,
			'growthDeferredIncomeTax' => true,
			'growthStockBasedCompensation' => true,
			'growthChangeInWorkingCapital' => true,
			'growthAccountsReceivables' => true,
			'growthInventory' => true,
			'growthAccountsPayables' => true,
			'growthOtherWorkingCapital' => true,
			'growthOtherNonCashItems' => true,
			'growthNetCashProvidedByOperatingActivites' => true,
			'growthInvestmentsInPropertyPlantAndEquipment' => true,
			'growthAcquisitionsNet' => true,
			'growthPurchasesOfInvestments' => true,
			'growthSalesMaturitiesOfInvestments' => true,
			'growthOtherInvestingActivites' => true,
			'growthNetCashUsedForInvestingActivites' => true,
			'growthDebtRepayment' => true,
			'growthCommonStockIssued' => true,
			'growthCommonStockRepurchased' => true,
			'growthDividendsPaid' => true,
			'growthOtherFinancingActivites' => true,
			'growthNetCashUsedProvidedByFinancingActivities' => true,
			'growthEffectOfForexChangesOnCash' => true,
			'growthNetChangeInCash' => true,
			'growthCashAtEndOfPeriod' => true,
			'growthCashAtBeginningOfPeriod' => true,
			'growthOperatingCashFlow' => true,
			'growthCapitalExpenditure' => true,
			'growthFreeCashFlow' => true,
		]));
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(CashFlowStatementGrowthBulk::class);
	}
}
