<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\CompanyProfile;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<CompanyProfile>
 */
final readonly class CompanyProfileMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|CompanyProfile
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'price' => $ts->optional($ts->nullable($ts->float())),
			'marketCap' => $ts->optional($ts->nullable($ts->int())),
			'beta' => $ts->optional($ts->nullable($ts->float())),
			'lastDividend' => $ts->optional($ts->nullable($ts->float())),
			'range' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'change' => $ts->optional($ts->nullable($ts->float())),
			'changePercentage' => $ts->optional($ts->nullable($ts->float())),
			'volume' => $ts->optional($ts->nullable($ts->union([$ts->int(), $ts->float()]))),
			'averageVolume' => $ts->optional($ts->nullable($ts->union([$ts->int(), $ts->float()]))),
			'companyName' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'currency' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'cik' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'isin' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'cusip' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'exchangeFullName' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'exchange' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'industry' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'website' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'description' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'ceo' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'sector' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'country' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'fullTimeEmployees' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'phone' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'address' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'city' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'state' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'zip' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'image' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'ipoDate' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'defaultImage' => $ts->optional($ts->nullable($ts->bool())),
			'isEtf' => $ts->optional($ts->nullable($ts->bool())),
			'isActivelyTrading' => $ts->optional($ts->nullable($ts->bool())),
			'isAdr' => $ts->optional($ts->nullable($ts->bool())),
			'isFund' => $ts->optional($ts->nullable($ts->bool())),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new CompanyProfile(...array_intersect_key($values, [
			'symbol' => true,
			'price' => true,
			'marketCap' => true,
			'beta' => true,
			'lastDividend' => true,
			'range' => true,
			'change' => true,
			'changePercentage' => true,
			'volume' => true,
			'averageVolume' => true,
			'companyName' => true,
			'currency' => true,
			'cik' => true,
			'isin' => true,
			'cusip' => true,
			'exchangeFullName' => true,
			'exchange' => true,
			'industry' => true,
			'website' => true,
			'description' => true,
			'ceo' => true,
			'sector' => true,
			'country' => true,
			'fullTimeEmployees' => true,
			'phone' => true,
			'address' => true,
			'city' => true,
			'state' => true,
			'zip' => true,
			'image' => true,
			'ipoDate' => true,
			'defaultImage' => true,
			'isEtf' => true,
			'isActivelyTrading' => true,
			'isAdr' => true,
			'isFund' => true,
		]));
	}


	public function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(CompanyProfile::class);
	}
}
