<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\Cryptocurrency;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<Cryptocurrency>
 */
final readonly class CryptocurrencyMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|Cryptocurrency
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'name' => $ts->string(),
			'exchange' => $ts->string(),
			'icoDate' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'circulatingSupply' => $ts->optional($ts->nullable($ts->union([$ts->int(), $ts->float()]))),
			'totalSupply' => $ts->optional($ts->nullable($ts->union([$ts->int(), $ts->float()]))),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new Cryptocurrency(...array_intersect_key($values, [
			'symbol' => true,
			'name' => true,
			'exchange' => true,
			'icoDate' => true,
			'circulatingSupply' => true,
			'totalSupply' => true,
		]));
	}


	public function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(Cryptocurrency::class);
	}
}
