<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\DetailedEarningsCalendarItem;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<DetailedEarningsCalendarItem>
 */
final readonly class DetailedEarningsCalendarItemMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|DetailedEarningsCalendarItem
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'epsActual' => $ts->nullable($ts->float()),
			'epsEstimated' => $ts->nullable($ts->float()),
			'revenueActual' => $ts->nullable($ts->union([$ts->int(), $ts->float()])),
			'revenueEstimated' => $ts->nullable($ts->union([$ts->int(), $ts->float()])),
			'time' => $ts->nullable($ts->nonEmptyString()),
			'periodEnding' => $ts->nullable($ts->nonEmptyString()),
			'confirmed' => $ts->bool(),
			'lastUpdated' => $ts->string(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new DetailedEarningsCalendarItem(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(DetailedEarningsCalendarItem::class);
	}
}
