<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Enum\Period;
use Shredio\FmpClient\Payload\DetailedEarningsCalendarItem;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<DetailedEarningsCalendarItem>
 */
final readonly class DetailedEarningsCalendarItemMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|DetailedEarningsCalendarItem
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'epsActual' => $ts->nullable($ts->float()),
			'epsEstimated' => $ts->nullable($ts->float()),
			'revenueActual' => $ts->nullable($ts->union([$ts->int(), $ts->float()])),
			'revenueEstimated' => $ts->nullable($ts->union([$ts->int(), $ts->float()])),
			'time' => $ts->nullable($ts->nonEmptyString()),
			'periodEnding' => $ts->nullable($ts->nonEmptyString()),
			'fiscalPeriod' => $ts->mapper(Period::class),
			'fiscalYear' => $ts->int(),
			'confirmed' => $ts->bool(),
			'lastUpdated' => $ts->string(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new DetailedEarningsCalendarItem(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(DetailedEarningsCalendarItem::class);
	}
}
