<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\DiscountedCashFlow;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<DiscountedCashFlow>
 */
final readonly class DiscountedCashFlowMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|DiscountedCashFlow
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'dcf' => $ts->optional($ts->nullable($ts->float())),
			'Stock Price' => $ts->optional($ts->nullable($ts->float())),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Reindex values
		if (array_key_exists('Stock Price', $values)) {
			$values['stockPrice'] = $values['Stock Price'];
			unset($values['Stock Price']);
		}

		// 4. Create a new instance
		return new DiscountedCashFlow(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(DiscountedCashFlow::class);
	}
}
