<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\Dividend;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<Dividend>
 */
final readonly class DividendMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|Dividend
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->nonEmptyString(),
			'recordDate' => $ts->nullable($ts->nonEmptyString()),
			'paymentDate' => $ts->nullable($ts->nonEmptyString()),
			'declarationDate' => $ts->nullable($ts->nonEmptyString()),
			'adjDividend' => $ts->float(),
			'dividend' => $ts->float(),
			'yield' => $ts->float(),
			'frequency' => $ts->string(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new Dividend(...$values);
	}


	public function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(Dividend::class);
	}
}
