<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\EconomicCalendarItem;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<EconomicCalendarItem>
 */
final readonly class EconomicCalendarItemMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|EconomicCalendarItem
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'date' => $ts->nonEmptyString(),
			'country' => $ts->nonEmptyString(),
			'event' => $ts->nonEmptyString(),
			'currency' => $ts->nonEmptyString(),
			'previous' => $ts->nullable($ts->float()),
			'estimate' => $ts->nullable($ts->float()),
			'actual' => $ts->nullable($ts->float()),
			'change' => $ts->nullable($ts->float()),
			'impact' => $ts->nonEmptyString(),
			'changePercentage' => $ts->nullable($ts->float()),
			'unit' => $ts->nullable($ts->nonEmptyString()),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new EconomicCalendarItem(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(EconomicCalendarItem::class);
	}
}
