<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\EodQuote;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<EodQuote>
 */
final readonly class EodQuoteMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|EodQuote
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'open' => $ts->float(),
			'low' => $ts->float(),
			'high' => $ts->float(),
			'close' => $ts->float(),
			'adjClose' => $ts->float(),
			'volume' => $ts->float(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new EodQuote(...array_intersect_key($values, [
			'symbol' => true,
			'date' => true,
			'open' => true,
			'low' => true,
			'high' => true,
			'close' => true,
			'adjClose' => true,
			'volume' => true,
		]));
	}


	public function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(EodQuote::class);
	}
}
