<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\ExchangeMarketHours;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<ExchangeMarketHours>
 */
final readonly class ExchangeMarketHoursMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|ExchangeMarketHours
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'exchange' => $ts->string(),
			'name' => $ts->string(),
			'openingHour' => $ts->string(),
			'closingHour' => $ts->string(),
			'timezone' => $ts->string(),
			'isMarketOpen' => $ts->bool(),
			'openingAdditional' => $ts->optional($ts->nullable($ts->nonEmptyString())),
			'closingAdditional' => $ts->optional($ts->nullable($ts->nonEmptyString())),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new ExchangeMarketHours(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(ExchangeMarketHours::class);
	}
}
