<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use PrinsFrank\Standards\Currency\CurrencyAlpha3;
use PrinsFrank\Standards\Currency\MinorUnits\CurrencyMinorLowerLastAlpha3;
use Shredio\FmpClient\Payload\FinancialStatementSymbol;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<FinancialStatementSymbol>
 */
final readonly class FinancialStatementSymbolMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|FinancialStatementSymbol
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'companyName' => $ts->string(),
			'tradingCurrency' => $ts->union([$ts->mapper(CurrencyAlpha3::class), $ts->mapper(CurrencyMinorLowerLastAlpha3::class)]),
			'reportingCurrency' => $ts->optional($ts->nullable($ts->union([$ts->mapper(CurrencyAlpha3::class), $ts->mapper(CurrencyMinorLowerLastAlpha3::class)]))),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new FinancialStatementSymbol(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(FinancialStatementSymbol::class);
	}
}
