<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\GradesConsensus;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<GradesConsensus>
 */
final readonly class GradesConsensusMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|GradesConsensus
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'strongBuy' => $ts->optional($ts->int()),
			'buy' => $ts->optional($ts->int()),
			'hold' => $ts->optional($ts->int()),
			'sell' => $ts->optional($ts->int()),
			'strongSell' => $ts->optional($ts->int()),
			'consensus' => $ts->optional($ts->string()),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new GradesConsensus(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(GradesConsensus::class);
	}
}
