<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\GradeNews;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<GradeNews>
 */
final readonly class GradeNewsMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|GradeNews
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'publishedDate' => $ts->nonEmptyString(),
			'newsURL' => $ts->string(),
			'newsTitle' => $ts->string(),
			'newsBaseURL' => $ts->string(),
			'newsPublisher' => $ts->string(),
			'newGrade' => $ts->string(),
			'previousGrade' => $ts->nullable($ts->string()),
			'gradingCompany' => $ts->string(),
			'action' => $ts->string(),
			'priceWhenPosted' => $ts->float(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new GradeNews(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(GradeNews::class);
	}
}
