<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\HistoricalPriceEodNonSplitAdjusted;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<HistoricalPriceEodNonSplitAdjusted>
 */
final readonly class HistoricalPriceEodNonSplitAdjustedMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|HistoricalPriceEodNonSplitAdjusted
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'adjOpen' => $ts->float(),
			'adjHigh' => $ts->float(),
			'adjLow' => $ts->float(),
			'adjClose' => $ts->float(),
			'volume' => $ts->int(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new HistoricalPriceEodNonSplitAdjusted(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(HistoricalPriceEodNonSplitAdjusted::class);
	}
}
