<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\HolidayByExchange;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<HolidayByExchange>
 */
final readonly class HolidayByExchangeMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|HolidayByExchange
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'exchange' => $ts->nonEmptyString(),
			'date' => $ts->nonEmptyString(),
			'name' => $ts->nonEmptyString(),
			'isClosed' => $ts->nullable($ts->bool()),
			'adjOpenTime' => $ts->nullable($ts->nonEmptyString()),
			'adjCloseTime' => $ts->nullable($ts->nonEmptyString()),
			'isFullyClosed' => $ts->optional($ts->nullable($ts->bool())),
		],
			identifier: 'exchange',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new HolidayByExchange(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(HolidayByExchange::class);
	}
}
