<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Enum\Period;
use Shredio\FmpClient\Payload\IncomeStatementGrowthBulk;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<IncomeStatementGrowthBulk>
 */
final readonly class IncomeStatementGrowthBulkMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|IncomeStatementGrowthBulk
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'calendarYear' => $ts->string(),
			'period' => $ts->mapper(Period::class),
			'growthRevenue' => $ts->float(),
			'growthCostOfRevenue' => $ts->float(),
			'growthGrossProfit' => $ts->float(),
			'growthGrossProfitRatio' => $ts->float(),
			'growthResearchAndDevelopmentExpenses' => $ts->float(),
			'growthGeneralAndAdministrativeExpenses' => $ts->float(),
			'growthSellingAndMarketingExpenses' => $ts->float(),
			'growthOtherExpenses' => $ts->float(),
			'growthOperatingExpenses' => $ts->float(),
			'growthCostAndExpenses' => $ts->float(),
			'growthInterestIncome' => $ts->float(),
			'growthInterestExpense' => $ts->float(),
			'growthDepreciationAndAmortization' => $ts->float(),
			'growthEBITDA' => $ts->float(),
			'growthOperatingIncome' => $ts->float(),
			'growthIncomeBeforeTax' => $ts->float(),
			'growthIncomeTaxExpense' => $ts->float(),
			'growthNetIncome' => $ts->float(),
			'growthEPS' => $ts->float(),
			'growthEPSDiluted' => $ts->float(),
			'growthWeightedAverageShsOut' => $ts->float(),
			'growthWeightedAverageShsOutDil' => $ts->float(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new IncomeStatementGrowthBulk(...array_intersect_key($values, [
			'symbol' => true,
			'date' => true,
			'calendarYear' => true,
			'period' => true,
			'growthRevenue' => true,
			'growthCostOfRevenue' => true,
			'growthGrossProfit' => true,
			'growthGrossProfitRatio' => true,
			'growthResearchAndDevelopmentExpenses' => true,
			'growthGeneralAndAdministrativeExpenses' => true,
			'growthSellingAndMarketingExpenses' => true,
			'growthOtherExpenses' => true,
			'growthOperatingExpenses' => true,
			'growthCostAndExpenses' => true,
			'growthInterestIncome' => true,
			'growthInterestExpense' => true,
			'growthDepreciationAndAmortization' => true,
			'growthEBITDA' => true,
			'growthOperatingIncome' => true,
			'growthIncomeBeforeTax' => true,
			'growthIncomeTaxExpense' => true,
			'growthNetIncome' => true,
			'growthEPS' => true,
			'growthEPSDiluted' => true,
			'growthWeightedAverageShsOut' => true,
			'growthWeightedAverageShsOutDil' => true,
		]));
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(IncomeStatementGrowthBulk::class);
	}
}
