<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Enum\Period;
use Shredio\FmpClient\Payload\IncomeStatement;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<IncomeStatement>
 */
final readonly class IncomeStatementMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|IncomeStatement
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'reportedCurrency' => $ts->string(),
			'cik' => $ts->string(),
			'filingDate' => $ts->string(),
			'acceptedDate' => $ts->string(),
			'fiscalYear' => $ts->string(),
			'period' => $ts->mapper(Period::class),
			'revenue' => $ts->optional($ts->float()),
			'costOfRevenue' => $ts->optional($ts->float()),
			'grossProfit' => $ts->optional($ts->float()),
			'researchAndDevelopmentExpenses' => $ts->optional($ts->float()),
			'generalAndAdministrativeExpenses' => $ts->optional($ts->float()),
			'sellingAndMarketingExpenses' => $ts->optional($ts->float()),
			'sellingGeneralAndAdministrativeExpenses' => $ts->optional($ts->float()),
			'otherExpenses' => $ts->optional($ts->float()),
			'operatingExpenses' => $ts->optional($ts->float()),
			'costAndExpenses' => $ts->optional($ts->float()),
			'netInterestIncome' => $ts->optional($ts->float()),
			'interestIncome' => $ts->optional($ts->float()),
			'interestExpense' => $ts->optional($ts->float()),
			'depreciationAndAmortization' => $ts->optional($ts->float()),
			'ebitda' => $ts->optional($ts->float()),
			'ebit' => $ts->optional($ts->float()),
			'nonOperatingIncomeExcludingInterest' => $ts->optional($ts->float()),
			'operatingIncome' => $ts->optional($ts->float()),
			'totalOtherIncomeExpensesNet' => $ts->optional($ts->float()),
			'incomeBeforeTax' => $ts->optional($ts->float()),
			'incomeTaxExpense' => $ts->optional($ts->float()),
			'netIncomeFromContinuingOperations' => $ts->optional($ts->float()),
			'netIncomeFromDiscontinuedOperations' => $ts->optional($ts->float()),
			'otherAdjustmentsToNetIncome' => $ts->optional($ts->float()),
			'netIncome' => $ts->optional($ts->float()),
			'netIncomeDeductions' => $ts->optional($ts->float()),
			'bottomLineNetIncome' => $ts->optional($ts->float()),
			'eps' => $ts->optional($ts->float()),
			'epsDiluted' => $ts->optional($ts->float()),
			'weightedAverageShsOut' => $ts->optional($ts->int()),
			'weightedAverageShsOutDil' => $ts->optional($ts->int()),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new IncomeStatement(...array_intersect_key($values, [
			'symbol' => true,
			'date' => true,
			'reportedCurrency' => true,
			'cik' => true,
			'filingDate' => true,
			'acceptedDate' => true,
			'fiscalYear' => true,
			'period' => true,
			'revenue' => true,
			'costOfRevenue' => true,
			'grossProfit' => true,
			'researchAndDevelopmentExpenses' => true,
			'generalAndAdministrativeExpenses' => true,
			'sellingAndMarketingExpenses' => true,
			'sellingGeneralAndAdministrativeExpenses' => true,
			'otherExpenses' => true,
			'operatingExpenses' => true,
			'costAndExpenses' => true,
			'netInterestIncome' => true,
			'interestIncome' => true,
			'interestExpense' => true,
			'depreciationAndAmortization' => true,
			'ebitda' => true,
			'ebit' => true,
			'nonOperatingIncomeExcludingInterest' => true,
			'operatingIncome' => true,
			'totalOtherIncomeExpensesNet' => true,
			'incomeBeforeTax' => true,
			'incomeTaxExpense' => true,
			'netIncomeFromContinuingOperations' => true,
			'netIncomeFromDiscontinuedOperations' => true,
			'otherAdjustmentsToNetIncome' => true,
			'netIncome' => true,
			'netIncomeDeductions' => true,
			'bottomLineNetIncome' => true,
			'eps' => true,
			'epsDiluted' => true,
			'weightedAverageShsOut' => true,
			'weightedAverageShsOutDil' => true,
		]));
	}


	public function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(IncomeStatement::class);
	}
}
