<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Enum\Period;
use Shredio\FmpClient\Payload\IncomeStatementGrowthBulk;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<IncomeStatementGrowthBulk>
 */
final readonly class IncomeStatementGrowthBulkMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|IncomeStatementGrowthBulk
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'calendarYear' => $ts->string(),
			'period' => $ts->mapper(Period::class),
			'growthRevenue' => $ts->float(),
			'growthCostOfRevenue' => $ts->float(),
			'growthGrossProfit' => $ts->float(),
			'growthGrossProfitRatio' => $ts->float(),
			'growthResearchAndDevelopmentExpenses' => $ts->float(),
			'growthGeneralAndAdministrativeExpenses' => $ts->float(),
			'growthSellingAndMarketingExpenses' => $ts->float(),
			'growthOtherExpenses' => $ts->float(),
			'growthOperatingExpenses' => $ts->float(),
			'growthCostAndExpenses' => $ts->float(),
			'growthInterestIncome' => $ts->float(),
			'growthInterestExpense' => $ts->float(),
			'growthDepreciationAndAmortization' => $ts->float(),
			'growthEBITDA' => $ts->float(),
			'growthOperatingIncome' => $ts->float(),
			'growthIncomeBeforeTax' => $ts->float(),
			'growthIncomeTaxExpense' => $ts->float(),
			'growthNetIncome' => $ts->float(),
			'growthEPS' => $ts->float(),
			'growthEPSDiluted' => $ts->float(),
			'growthWeightedAverageShsOut' => $ts->float(),
			'growthWeightedAverageShsOutDil' => $ts->float(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new IncomeStatementGrowthBulk(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(IncomeStatementGrowthBulk::class);
	}
}
