<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Enum\Period;
use Shredio\FmpClient\Payload\IncomeStatementGrowth;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<IncomeStatementGrowth>
 */
final readonly class IncomeStatementGrowthMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|IncomeStatementGrowth
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'date' => $ts->string(),
			'symbol' => $ts->nonEmptyString(),
			'calendarYear' => $ts->string(),
			'period' => $ts->mapper(Period::class),
			'growthRevenue' => $ts->float(),
			'growthCostOfRevenue' => $ts->float(),
			'growthGrossProfit' => $ts->float(),
			'growthGrossProfitRatio' => $ts->float(),
			'growthResearchAndDevelopmentExpenses' => $ts->float(),
			'growthGeneralAndAdministrativeExpenses' => $ts->float(),
			'growthSellingAndMarketingExpenses' => $ts->float(),
			'growthOtherExpenses' => $ts->float(),
			'growthOperatingExpenses' => $ts->float(),
			'growthCostAndExpenses' => $ts->float(),
			'growthInterestExpense' => $ts->float(),
			'growthDepreciationAndAmortization' => $ts->float(),
			'growthEBITDA' => $ts->float(),
			'growthEBITDARatio' => $ts->float(),
			'growthOperatingIncome' => $ts->float(),
			'growthOperatingIncomeRatio' => $ts->float(),
			'growthTotalOtherIncomeExpensesNet' => $ts->float(),
			'growthIncomeBeforeTax' => $ts->float(),
			'growthIncomeBeforeTaxRatio' => $ts->float(),
			'growthIncomeTaxExpense' => $ts->float(),
			'growthNetIncome' => $ts->float(),
			'growthNetIncomeRatio' => $ts->float(),
			'growthEPS' => $ts->float(),
			'growthEPSDiluted' => $ts->float(),
			'growthWeightedAverageShsOut' => $ts->float(),
			'growthWeightedAverageShsOutDil' => $ts->float(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new IncomeStatementGrowth(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(IncomeStatementGrowth::class);
	}
}
