<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\InsiderTradeStatistics;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<InsiderTradeStatistics>
 */
final readonly class InsiderTradeStatisticsMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|InsiderTradeStatistics
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'cik' => $ts->string(),
			'year' => $ts->int(),
			'quarter' => $ts->intRange(1, 4),
			'acquiredTransactions' => $ts->int(),
			'disposedTransactions' => $ts->int(),
			'acquiredDisposedRatio' => $ts->float(),
			'totalAcquired' => $ts->union([$ts->int(), $ts->float()]),
			'totalDisposed' => $ts->union([$ts->int(), $ts->float()]),
			'averageAcquired' => $ts->float(),
			'averageDisposed' => $ts->float(),
			'totalPurchases' => $ts->int(),
			'totalSales' => $ts->int(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new InsiderTradeStatistics(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(InsiderTradeStatistics::class);
	}
}
