<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\InsiderTrade;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<InsiderTrade>
 */
final readonly class InsiderTradeMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|InsiderTrade
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'filingDate' => $ts->nonEmptyString(),
			'transactionDate' => $ts->nonEmptyString(),
			'reportingCik' => $ts->string(),
			'companyCik' => $ts->string(),
			'transactionType' => $ts->string(),
			'securitiesOwned' => $ts->union([$ts->int(), $ts->float()]),
			'reportingName' => $ts->string(),
			'typeOfOwner' => $ts->string(),
			'acquisitionOrDisposition' => $ts->string(),
			'directOrIndirect' => $ts->nonEmptyString(),
			'formType' => $ts->string(),
			'securitiesTransacted' => $ts->union([$ts->int(), $ts->float()]),
			'price' => $ts->float(),
			'securityName' => $ts->string(),
			'url' => $ts->string(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new InsiderTrade(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(InsiderTrade::class);
	}
}
