<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\InstitutionalPositionsSummary;
use Shredio\FmpClient\TypeSchema\MoneyAmount;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<InstitutionalPositionsSummary>
 */
final readonly class InstitutionalPositionsSummaryMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|InstitutionalPositionsSummary
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'cik' => $ts->string(),
			'date' => $ts->nonEmptyString(),
			'investorsHolding' => $ts->int(),
			'lastInvestorsHolding' => $ts->int(),
			'investorsHoldingChange' => $ts->int(),
			'numberOf13Fshares' => $ts->int(),
			'lastNumberOf13Fshares' => $ts->int(),
			'numberOf13FsharesChange' => $ts->int(),
			'totalInvested' => $ts->before(MoneyAmount::roundToInt(...), $ts->int()),
			'lastTotalInvested' => $ts->before(MoneyAmount::roundToInt(...), $ts->int()),
			'totalInvestedChange' => $ts->before(MoneyAmount::roundToInt(...), $ts->int()),
			'ownershipPercent' => $ts->float(),
			'lastOwnershipPercent' => $ts->float(),
			'ownershipPercentChange' => $ts->float(),
			'newPositions' => $ts->int(),
			'lastNewPositions' => $ts->int(),
			'newPositionsChange' => $ts->int(),
			'increasedPositions' => $ts->int(),
			'lastIncreasedPositions' => $ts->int(),
			'increasedPositionsChange' => $ts->int(),
			'closedPositions' => $ts->int(),
			'lastClosedPositions' => $ts->int(),
			'closedPositionsChange' => $ts->int(),
			'reducedPositions' => $ts->int(),
			'lastReducedPositions' => $ts->int(),
			'reducedPositionsChange' => $ts->int(),
			'totalCalls' => $ts->int(),
			'lastTotalCalls' => $ts->int(),
			'totalCallsChange' => $ts->int(),
			'totalPuts' => $ts->int(),
			'lastTotalPuts' => $ts->int(),
			'totalPutsChange' => $ts->int(),
			'putCallRatio' => $ts->float(),
			'lastPutCallRatio' => $ts->float(),
			'putCallRatioChange' => $ts->float(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new InstitutionalPositionsSummary(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(InstitutionalPositionsSummary::class);
	}
}
