<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\InstitutionalHolder;
use Shredio\FmpClient\TypeSchema\MoneyAmount;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<InstitutionalHolder>
 */
final readonly class InstitutionalHolderMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|InstitutionalHolder
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'date' => $ts->nonEmptyString(),
			'cik' => $ts->string(),
			'filingDate' => $ts->nonEmptyString(),
			'investorName' => $ts->string(),
			'symbol' => $ts->nonEmptyString(),
			'securityName' => $ts->string(),
			'typeOfSecurity' => $ts->string(),
			'securityCusip' => $ts->string(),
			'sharesType' => $ts->string(),
			'putCallShare' => $ts->string(),
			'investmentDiscretion' => $ts->string(),
			'industryTitle' => $ts->string(),
			'weight' => $ts->float(),
			'lastWeight' => $ts->float(),
			'changeInWeight' => $ts->float(),
			'changeInWeightPercentage' => $ts->float(),
			'marketValue' => $ts->before(MoneyAmount::roundToInt(...), $ts->int()),
			'lastMarketValue' => $ts->before(MoneyAmount::roundToInt(...), $ts->int()),
			'changeInMarketValue' => $ts->before(MoneyAmount::roundToInt(...), $ts->int()),
			'changeInMarketValuePercentage' => $ts->float(),
			'sharesNumber' => $ts->int(),
			'lastSharesNumber' => $ts->int(),
			'changeInSharesNumber' => $ts->int(),
			'changeInSharesNumberPercentage' => $ts->float(),
			'quarterEndPrice' => $ts->float(),
			'avgPricePaid' => $ts->float(),
			'isNew' => $ts->bool(),
			'isSoldOut' => $ts->bool(),
			'ownership' => $ts->float(),
			'lastOwnership' => $ts->float(),
			'changeInOwnership' => $ts->float(),
			'changeInOwnershipPercentage' => $ts->float(),
			'holdingPeriod' => $ts->int(),
			'firstAdded' => $ts->nonEmptyString(),
			'performance' => $ts->before(MoneyAmount::roundToInt(...), $ts->int()),
			'performancePercentage' => $ts->float(),
			'lastPerformance' => $ts->before(MoneyAmount::roundToInt(...), $ts->int()),
			'changeInPerformance' => $ts->before(MoneyAmount::roundToInt(...), $ts->int()),
			'isCountedForPerformance' => $ts->bool(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new InstitutionalHolder(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(InstitutionalHolder::class);
	}
}
