<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\InstitutionalOwnershipFiling;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<InstitutionalOwnershipFiling>
 */
final readonly class InstitutionalOwnershipFilingMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|InstitutionalOwnershipFiling
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'cik' => $ts->nonEmptyString(),
			'name' => $ts->string(),
			'date' => $ts->nonEmptyString(),
			'filingDate' => $ts->nonEmptyString(),
			'acceptedDate' => $ts->nonEmptyString(),
			'formType' => $ts->string(),
			'link' => $ts->string(),
			'finalLink' => $ts->string(),
		],
			identifier: 'cik',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new InstitutionalOwnershipFiling(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(InstitutionalOwnershipFiling::class);
	}
}
