<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Enum\Period;
use Shredio\FmpClient\Payload\KeyMetrics;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<KeyMetrics>
 */
final readonly class KeyMetricsMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|KeyMetrics
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'fiscalYear' => $ts->string(),
			'period' => $ts->mapper(Period::class),
			'reportedCurrency' => $ts->string(),
			'marketCap' => $ts->optional($ts->nullable($ts->int())),
			'enterpriseValue' => $ts->optional($ts->nullable($ts->int())),
			'evToSales' => $ts->optional($ts->nullable($ts->float())),
			'evToOperatingCashFlow' => $ts->optional($ts->nullable($ts->float())),
			'evToFreeCashFlow' => $ts->optional($ts->nullable($ts->float())),
			'evToEBITDA' => $ts->optional($ts->nullable($ts->float())),
			'netDebtToEBITDA' => $ts->optional($ts->nullable($ts->float())),
			'currentRatio' => $ts->optional($ts->nullable($ts->float())),
			'incomeQuality' => $ts->optional($ts->nullable($ts->float())),
			'grahamNumber' => $ts->optional($ts->nullable($ts->float())),
			'grahamNetNet' => $ts->optional($ts->nullable($ts->float())),
			'taxBurden' => $ts->optional($ts->nullable($ts->float())),
			'interestBurden' => $ts->optional($ts->nullable($ts->float())),
			'workingCapital' => $ts->optional($ts->nullable($ts->int())),
			'investedCapital' => $ts->optional($ts->nullable($ts->int())),
			'returnOnAssets' => $ts->optional($ts->nullable($ts->float())),
			'operatingReturnOnAssets' => $ts->optional($ts->nullable($ts->float())),
			'returnOnTangibleAssets' => $ts->optional($ts->nullable($ts->float())),
			'returnOnEquity' => $ts->optional($ts->nullable($ts->float())),
			'returnOnInvestedCapital' => $ts->optional($ts->nullable($ts->float())),
			'returnOnCapitalEmployed' => $ts->optional($ts->nullable($ts->float())),
			'earningsYield' => $ts->optional($ts->nullable($ts->float())),
			'freeCashFlowYield' => $ts->optional($ts->nullable($ts->float())),
			'capexToOperatingCashFlow' => $ts->optional($ts->nullable($ts->float())),
			'capexToDepreciation' => $ts->optional($ts->nullable($ts->float())),
			'capexToRevenue' => $ts->optional($ts->nullable($ts->float())),
			'salesGeneralAndAdministrativeToRevenue' => $ts->optional($ts->nullable($ts->float())),
			'researchAndDevelopementToRevenue' => $ts->optional($ts->nullable($ts->float())),
			'stockBasedCompensationToRevenue' => $ts->optional($ts->nullable($ts->float())),
			'intangiblesToTotalAssets' => $ts->optional($ts->nullable($ts->float())),
			'averageReceivables' => $ts->optional($ts->nullable($ts->float())),
			'averagePayables' => $ts->optional($ts->nullable($ts->float())),
			'averageInventory' => $ts->optional($ts->nullable($ts->float())),
			'daysOfSalesOutstanding' => $ts->optional($ts->nullable($ts->float())),
			'daysOfPayablesOutstanding' => $ts->optional($ts->nullable($ts->float())),
			'daysOfInventoryOutstanding' => $ts->optional($ts->nullable($ts->float())),
			'operatingCycle' => $ts->optional($ts->nullable($ts->float())),
			'cashConversionCycle' => $ts->optional($ts->nullable($ts->float())),
			'freeCashFlowToEquity' => $ts->optional($ts->nullable($ts->float())),
			'freeCashFlowToFirm' => $ts->optional($ts->nullable($ts->float())),
			'tangibleAssetValue' => $ts->optional($ts->nullable($ts->int())),
			'netCurrentAssetValue' => $ts->optional($ts->nullable($ts->int())),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new KeyMetrics(...$values);
	}


	public function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(KeyMetrics::class);
	}
}
