<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\LatestSenateTrade;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Result\Failure;
use Shredio\TypeSchema\Result\WithNotices;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<LatestSenateTrade>
 */
final readonly class LatestSenateTradeMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): Failure|WithNotices|LatestSenateTrade
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape([
			'symbol' => $ts->string(),
			'senateID' => $ts->nullable($ts->nonEmptyString()),
			'disclosureDate' => $ts->nonEmptyString(),
			'transactionDate' => $ts->nonEmptyString(),
			'firstName' => $ts->string(),
			'lastName' => $ts->string(),
			'office' => $ts->string(),
			'district' => $ts->string(),
			'owner' => $ts->string(),
			'assetDescription' => $ts->string(),
			'assetType' => $ts->string(),
			'type' => $ts->string(),
			'amount' => $ts->nonEmptyString(),
			'comment' => $ts->string(),
			'link' => $ts->string(),
		]);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($values instanceof Failure) {
			return $this->withOwnDefinition($values, $context);
		}

		$notices = null;
		if ($values instanceof WithNotices) {
			$notices = $values->notices;
			$values = $values->value;
		}

		// 3. Create a new instance
		$obj = new LatestSenateTrade(...$values);

		return $notices === null ? $obj : new WithNotices($obj, $notices);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(LatestSenateTrade::class);
	}
}
