<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\MarketRiskPremium;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<MarketRiskPremium>
 */
final readonly class MarketRiskPremiumMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|MarketRiskPremium
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'country' => $ts->nonEmptyString(),
			'continent' => $ts->nonEmptyString(),
			'countryRiskPremium' => $ts->float(),
			'totalEquityRiskPremium' => $ts->float(),
		],
			identifier: 'country',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new MarketRiskPremium(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(MarketRiskPremium::class);
	}
}
