<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\PressRelease;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<PressRelease>
 */
final readonly class PressReleaseMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|PressRelease
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'publishedDate' => $ts->nonEmptyString(),
			'publisher' => $ts->nonEmptyString(),
			'title' => $ts->nonEmptyString(),
			'image' => $ts->nullable($ts->nonEmptyString()),
			'site' => $ts->nonEmptyString(),
			'text' => $ts->nonEmptyString(),
			'url' => $ts->nonEmptyString(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new PressRelease(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(PressRelease::class);
	}
}
