<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\PriceTargetConsensus;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<PriceTargetConsensus>
 */
final readonly class PriceTargetConsensusMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|PriceTargetConsensus
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'targetHigh' => $ts->optional($ts->nullable($ts->float())),
			'targetLow' => $ts->optional($ts->nullable($ts->float())),
			'targetConsensus' => $ts->optional($ts->nullable($ts->float())),
			'targetMedian' => $ts->optional($ts->nullable($ts->float())),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new PriceTargetConsensus(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(PriceTargetConsensus::class);
	}
}
