<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Enum\Period;
use Shredio\FmpClient\Payload\Ratios;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<Ratios>
 */
final readonly class RatiosMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|Ratios
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'fiscalYear' => $ts->string(),
			'period' => $ts->mapper(Period::class),
			'reportedCurrency' => $ts->string(),
			'grossProfitMargin' => $ts->optional($ts->nullable($ts->float())),
			'ebitMargin' => $ts->optional($ts->nullable($ts->float())),
			'ebitdaMargin' => $ts->optional($ts->nullable($ts->float())),
			'operatingProfitMargin' => $ts->optional($ts->nullable($ts->float())),
			'pretaxProfitMargin' => $ts->optional($ts->nullable($ts->float())),
			'continuousOperationsProfitMargin' => $ts->optional($ts->nullable($ts->float())),
			'netProfitMargin' => $ts->optional($ts->nullable($ts->float())),
			'bottomLineProfitMargin' => $ts->optional($ts->nullable($ts->float())),
			'receivablesTurnover' => $ts->optional($ts->nullable($ts->float())),
			'payablesTurnover' => $ts->optional($ts->nullable($ts->float())),
			'inventoryTurnover' => $ts->optional($ts->nullable($ts->float())),
			'fixedAssetTurnover' => $ts->optional($ts->nullable($ts->float())),
			'assetTurnover' => $ts->optional($ts->nullable($ts->float())),
			'currentRatio' => $ts->optional($ts->nullable($ts->float())),
			'quickRatio' => $ts->optional($ts->nullable($ts->float())),
			'solvencyRatio' => $ts->optional($ts->nullable($ts->float())),
			'cashRatio' => $ts->optional($ts->nullable($ts->float())),
			'priceToEarningsRatio' => $ts->optional($ts->nullable($ts->float())),
			'priceToEarningsGrowthRatio' => $ts->optional($ts->nullable($ts->float())),
			'forwardPriceToEarningsGrowthRatio' => $ts->optional($ts->nullable($ts->float())),
			'priceToBookRatio' => $ts->optional($ts->nullable($ts->float())),
			'priceToSalesRatio' => $ts->optional($ts->nullable($ts->float())),
			'priceToFreeCashFlowRatio' => $ts->optional($ts->nullable($ts->float())),
			'priceToOperatingCashFlowRatio' => $ts->optional($ts->nullable($ts->float())),
			'debtToAssetsRatio' => $ts->optional($ts->nullable($ts->float())),
			'debtToEquityRatio' => $ts->optional($ts->nullable($ts->float())),
			'debtToCapitalRatio' => $ts->optional($ts->nullable($ts->float())),
			'longTermDebtToCapitalRatio' => $ts->optional($ts->nullable($ts->float())),
			'financialLeverageRatio' => $ts->optional($ts->nullable($ts->float())),
			'workingCapitalTurnoverRatio' => $ts->optional($ts->nullable($ts->float())),
			'operatingCashFlowRatio' => $ts->optional($ts->nullable($ts->float())),
			'operatingCashFlowSalesRatio' => $ts->optional($ts->nullable($ts->float())),
			'freeCashFlowOperatingCashFlowRatio' => $ts->optional($ts->nullable($ts->float())),
			'debtServiceCoverageRatio' => $ts->optional($ts->nullable($ts->float())),
			'interestCoverageRatio' => $ts->optional($ts->nullable($ts->float())),
			'shortTermOperatingCashFlowCoverageRatio' => $ts->optional($ts->nullable($ts->float())),
			'operatingCashFlowCoverageRatio' => $ts->optional($ts->nullable($ts->float())),
			'capitalExpenditureCoverageRatio' => $ts->optional($ts->nullable($ts->float())),
			'dividendPaidAndCapexCoverageRatio' => $ts->optional($ts->nullable($ts->float())),
			'dividendPayoutRatio' => $ts->optional($ts->nullable($ts->float())),
			'dividendYield' => $ts->optional($ts->nullable($ts->float())),
			'dividendYieldPercentage' => $ts->optional($ts->nullable($ts->float())),
			'revenuePerShare' => $ts->optional($ts->nullable($ts->float())),
			'netIncomePerShare' => $ts->optional($ts->nullable($ts->float())),
			'interestDebtPerShare' => $ts->optional($ts->nullable($ts->float())),
			'cashPerShare' => $ts->optional($ts->nullable($ts->float())),
			'bookValuePerShare' => $ts->optional($ts->nullable($ts->float())),
			'tangibleBookValuePerShare' => $ts->optional($ts->nullable($ts->float())),
			'shareholdersEquityPerShare' => $ts->optional($ts->nullable($ts->float())),
			'operatingCashFlowPerShare' => $ts->optional($ts->nullable($ts->float())),
			'capexPerShare' => $ts->optional($ts->nullable($ts->float())),
			'freeCashFlowPerShare' => $ts->optional($ts->nullable($ts->float())),
			'netIncomePerEBT' => $ts->optional($ts->nullable($ts->float())),
			'ebtPerEbit' => $ts->optional($ts->nullable($ts->float())),
			'priceToFairValue' => $ts->optional($ts->nullable($ts->float())),
			'debtToMarketCap' => $ts->optional($ts->nullable($ts->float())),
			'effectiveTaxRate' => $ts->optional($ts->nullable($ts->float())),
			'enterpriseValueMultiple' => $ts->optional($ts->nullable($ts->float())),
			'dividendPerShare' => $ts->optional($ts->nullable($ts->float())),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new Ratios(...array_intersect_key($values, [
			'symbol' => true,
			'date' => true,
			'fiscalYear' => true,
			'period' => true,
			'reportedCurrency' => true,
			'grossProfitMargin' => true,
			'ebitMargin' => true,
			'ebitdaMargin' => true,
			'operatingProfitMargin' => true,
			'pretaxProfitMargin' => true,
			'continuousOperationsProfitMargin' => true,
			'netProfitMargin' => true,
			'bottomLineProfitMargin' => true,
			'receivablesTurnover' => true,
			'payablesTurnover' => true,
			'inventoryTurnover' => true,
			'fixedAssetTurnover' => true,
			'assetTurnover' => true,
			'currentRatio' => true,
			'quickRatio' => true,
			'solvencyRatio' => true,
			'cashRatio' => true,
			'priceToEarningsRatio' => true,
			'priceToEarningsGrowthRatio' => true,
			'forwardPriceToEarningsGrowthRatio' => true,
			'priceToBookRatio' => true,
			'priceToSalesRatio' => true,
			'priceToFreeCashFlowRatio' => true,
			'priceToOperatingCashFlowRatio' => true,
			'debtToAssetsRatio' => true,
			'debtToEquityRatio' => true,
			'debtToCapitalRatio' => true,
			'longTermDebtToCapitalRatio' => true,
			'financialLeverageRatio' => true,
			'workingCapitalTurnoverRatio' => true,
			'operatingCashFlowRatio' => true,
			'operatingCashFlowSalesRatio' => true,
			'freeCashFlowOperatingCashFlowRatio' => true,
			'debtServiceCoverageRatio' => true,
			'interestCoverageRatio' => true,
			'shortTermOperatingCashFlowCoverageRatio' => true,
			'operatingCashFlowCoverageRatio' => true,
			'capitalExpenditureCoverageRatio' => true,
			'dividendPaidAndCapexCoverageRatio' => true,
			'dividendPayoutRatio' => true,
			'dividendYield' => true,
			'dividendYieldPercentage' => true,
			'revenuePerShare' => true,
			'netIncomePerShare' => true,
			'interestDebtPerShare' => true,
			'cashPerShare' => true,
			'bookValuePerShare' => true,
			'tangibleBookValuePerShare' => true,
			'shareholdersEquityPerShare' => true,
			'operatingCashFlowPerShare' => true,
			'capexPerShare' => true,
			'freeCashFlowPerShare' => true,
			'netIncomePerEBT' => true,
			'ebtPerEbit' => true,
			'priceToFairValue' => true,
			'debtToMarketCap' => true,
			'effectiveTaxRate' => true,
			'enterpriseValueMultiple' => true,
			'dividendPerShare' => true,
		]));
	}


	public function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(Ratios::class);
	}
}
