<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Enum\Period;
use Shredio\FmpClient\Payload\RevenueProductSegmentation;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<RevenueProductSegmentation>
 */
final readonly class RevenueProductSegmentationMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|RevenueProductSegmentation
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'fiscalYear' => $ts->int(),
			'period' => $ts->mapper(Period::class),
			'reportedCurrency' => $ts->string(),
			'date' => $ts->string(),
			'data' => $ts->optional($ts->array($ts->string(), $ts->float())),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new RevenueProductSegmentation(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(RevenueProductSegmentation::class);
	}
}
