<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\Scores;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<Scores>
 */
final readonly class ScoresMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|Scores
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'reportedCurrency' => $ts->string(),
			'altmanZScore' => $ts->optional($ts->nullable($ts->float())),
			'piotroskiScore' => $ts->optional($ts->nullable($ts->int())),
			'workingCapital' => $ts->optional($ts->nullable($ts->union([$ts->int(), $ts->float()]))),
			'totalAssets' => $ts->optional($ts->nullable($ts->union([$ts->int(), $ts->float()]))),
			'retainedEarnings' => $ts->optional($ts->nullable($ts->union([$ts->int(), $ts->float()]))),
			'ebit' => $ts->optional($ts->nullable($ts->union([$ts->int(), $ts->float()]))),
			'marketCap' => $ts->optional($ts->nullable($ts->union([$ts->int(), $ts->float()]))),
			'totalLiabilities' => $ts->optional($ts->nullable($ts->union([$ts->int(), $ts->float()]))),
			'revenue' => $ts->optional($ts->nullable($ts->union([$ts->int(), $ts->float()]))),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new Scores(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(Scores::class);
	}
}
