<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\SenateTrade;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<SenateTrade>
 */
final readonly class SenateTradeMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|SenateTrade
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'senateID' => $ts->nullable($ts->nonEmptyString()),
			'disclosureDate' => $ts->nonEmptyString(),
			'transactionDate' => $ts->nonEmptyString(),
			'firstName' => $ts->string(),
			'lastName' => $ts->string(),
			'office' => $ts->string(),
			'district' => $ts->string(),
			'owner' => $ts->string(),
			'assetDescription' => $ts->string(),
			'assetType' => $ts->string(),
			'type' => $ts->string(),
			'amount' => $ts->nonEmptyString(),
			'comment' => $ts->string(),
			'link' => $ts->string(),
			'capitalGainsOver200USD' => $ts->optional($ts->nullable($ts->string())),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new SenateTrade(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(SenateTrade::class);
	}
}
