<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\SplitsCalendarItem;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<SplitsCalendarItem>
 */
final readonly class SplitsCalendarItemMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|SplitsCalendarItem
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'symbol' => $ts->nonEmptyString(),
			'date' => $ts->string(),
			'numerator' => $ts->int(),
			'denominator' => $ts->int(),
		],
			identifier: 'symbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new SplitsCalendarItem(...array_intersect_key($values, [
			'symbol' => true,
			'date' => true,
			'numerator' => true,
			'denominator' => true,
		]));
	}


	public function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(SplitsCalendarItem::class);
	}
}
