<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\SymbolChange;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<SymbolChange>
 */
final readonly class SymbolChangeMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|SymbolChange
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'date' => $ts->nonEmptyString(),
			'companyName' => $ts->nonEmptyString(),
			'oldSymbol' => $ts->nonEmptyString(),
			'newSymbol' => $ts->nonEmptyString(),
		],
			identifier: 'oldSymbol',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new SymbolChange(...array_intersect_key($values, [
			'date' => true,
			'companyName' => true,
			'oldSymbol' => true,
			'newSymbol' => true,
		]));
	}


	public function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(SymbolChange::class);
	}
}
