<?php

declare(strict_types=1);

namespace Shredio\FmpClient\Mapper;

use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use Shredio\FmpClient\Payload\TreasuryRate;
use Shredio\TypeSchema\Context\TypeContext;
use Shredio\TypeSchema\Error\ErrorElement;
use Shredio\TypeSchema\TypeSchema;
use Shredio\TypeSchema\Types\Type;

/**
 * This class was generated by the compiler. Do not modify it manually.
 *
 * @extends Type<TreasuryRate>
 */
final readonly class TreasuryRateMapper extends Type
{
	public function parse(mixed $valueToParse, TypeContext $context): ErrorElement|TreasuryRate
	{
		// 0. Initialize TypeSchema
		$ts = TypeSchema::get();

		// 1. Define schema
		$schema = $ts->arrayShape(
			[
			'date' => $ts->nonEmptyString(),
			'month1' => $ts->float(),
			'month2' => $ts->float(),
			'month3' => $ts->float(),
			'month6' => $ts->float(),
			'year1' => $ts->float(),
			'year2' => $ts->float(),
			'year3' => $ts->float(),
			'year5' => $ts->float(),
			'year7' => $ts->float(),
			'year10' => $ts->float(),
			'year20' => $ts->float(),
			'year30' => $ts->float(),
		],
			identifier: 'date',
		);

		// 2. Map values
		$values = $schema->parse($valueToParse, $context);
		if ($this->isError($values)) {
			return $values;
		}

		// 3. Create a new instance
		return new TreasuryRate(...$values);
	}


	protected function getTypeNode(TypeContext $context): TypeNode
	{
		return new IdentifierTypeNode(TreasuryRate::class);
	}
}
