<?php declare(strict_types = 1);

namespace Shredio\FmpClient\Payload;

use Shredio\FmpClient\Enum\Period;

final readonly class BalanceSheetStatement
{

	public function __construct(
		public string $symbol,
		public string $date,
		public string $reportedCurrency,
		public string $cik,
		public string $filingDate,
		public string $acceptedDate,
		public string $fiscalYear,
		public Period $period,
		public int $cashAndCashEquivalents = 0,
		public int $shortTermInvestments = 0,
		public int $cashAndShortTermInvestments = 0,
		public int $netReceivables = 0,
		public int $accountsReceivables = 0,
		public int $otherReceivables = 0,
		public int $inventory = 0,
		public int $prepaids = 0,
		public int $otherCurrentAssets = 0,
		public int $totalCurrentAssets = 0,
		public int $propertyPlantEquipmentNet = 0,
		public int $goodwill = 0,
		public int $intangibleAssets = 0,
		public int $goodwillAndIntangibleAssets = 0,
		public int $longTermInvestments = 0,
		public int $taxAssets = 0,
		public int $otherNonCurrentAssets = 0,
		public int $totalNonCurrentAssets = 0,
		public int $otherAssets = 0,
		public int $totalAssets = 0,
		public int $totalPayables = 0,
		public int $accountPayables = 0,
		public int $otherPayables = 0,
		public int $accruedExpenses = 0,
		public int $shortTermDebt = 0,
		public int $capitalLeaseObligationsCurrent = 0,
		public int $taxPayables = 0,
		public int $deferredRevenue = 0,
		public int $otherCurrentLiabilities = 0,
		public int $totalCurrentLiabilities = 0,
		public int $longTermDebt = 0,
		public int $capitalLeaseObligationsNonCurrent = 0,
		public int $deferredRevenueNonCurrent = 0,
		public int $deferredTaxLiabilitiesNonCurrent = 0,
		public int $otherNonCurrentLiabilities = 0,
		public int $totalNonCurrentLiabilities = 0,
		public int $otherLiabilities = 0,
		public int $capitalLeaseObligations = 0,
		public int $totalLiabilities = 0,
		public int $treasuryStock = 0,
		public int $preferredStock = 0,
		public int $commonStock = 0,
		public int $retainedEarnings = 0,
		public int $additionalPaidInCapital = 0,
		public int $accumulatedOtherComprehensiveIncomeLoss = 0,
		public int $otherTotalStockholdersEquity = 0,
		public int $totalStockholdersEquity = 0,
		public int $totalEquity = 0,
		public int $minorityInterest = 0,
		public int $totalLiabilitiesAndTotalEquity = 0,
		public int $totalInvestments = 0,
		public int $totalDebt = 0,
		public int $netDebt = 0,
	)
	{
	}

	/**
	 * @return array{symbol: string, date: string, reportedCurrency: string, cik: string, filingDate: string, acceptedDate: string, fiscalYear: string, period: string, cashAndCashEquivalents: int, shortTermInvestments: int, cashAndShortTermInvestments: int, netReceivables: int, accountsReceivables: int, otherReceivables: int, inventory: int, prepaids: int, otherCurrentAssets: int, totalCurrentAssets: int, propertyPlantEquipmentNet: int, goodwill: int, intangibleAssets: int, goodwillAndIntangibleAssets: int, longTermInvestments: int, taxAssets: int, otherNonCurrentAssets: int, totalNonCurrentAssets: int, otherAssets: int, totalAssets: int, totalPayables: int, accountPayables: int, otherPayables: int, accruedExpenses: int, shortTermDebt: int, capitalLeaseObligationsCurrent: int, taxPayables: int, deferredRevenue: int, otherCurrentLiabilities: int, totalCurrentLiabilities: int, longTermDebt: int, capitalLeaseObligationsNonCurrent: int, deferredRevenueNonCurrent: int, deferredTaxLiabilitiesNonCurrent: int, otherNonCurrentLiabilities: int, totalNonCurrentLiabilities: int, otherLiabilities: int, capitalLeaseObligations: int, totalLiabilities: int, treasuryStock: int, preferredStock: int, commonStock: int, retainedEarnings: int, additionalPaidInCapital: int, accumulatedOtherComprehensiveIncomeLoss: int, otherTotalStockholdersEquity: int, totalStockholdersEquity: int, totalEquity: int, minorityInterest: int, totalLiabilitiesAndTotalEquity: int, totalInvestments: int, totalDebt: int, netDebt: int}
	 */
	public function toArray(): array
	{
		return [
			'symbol' => $this->symbol,
			'date' => $this->date,
			'reportedCurrency' => $this->reportedCurrency,
			'cik' => $this->cik,
			'filingDate' => $this->filingDate,
			'acceptedDate' => $this->acceptedDate,
			'fiscalYear' => $this->fiscalYear,
			'period' => $this->period->value,
			'cashAndCashEquivalents' => $this->cashAndCashEquivalents,
			'shortTermInvestments' => $this->shortTermInvestments,
			'cashAndShortTermInvestments' => $this->cashAndShortTermInvestments,
			'netReceivables' => $this->netReceivables,
			'accountsReceivables' => $this->accountsReceivables,
			'otherReceivables' => $this->otherReceivables,
			'inventory' => $this->inventory,
			'prepaids' => $this->prepaids,
			'otherCurrentAssets' => $this->otherCurrentAssets,
			'totalCurrentAssets' => $this->totalCurrentAssets,
			'propertyPlantEquipmentNet' => $this->propertyPlantEquipmentNet,
			'goodwill' => $this->goodwill,
			'intangibleAssets' => $this->intangibleAssets,
			'goodwillAndIntangibleAssets' => $this->goodwillAndIntangibleAssets,
			'longTermInvestments' => $this->longTermInvestments,
			'taxAssets' => $this->taxAssets,
			'otherNonCurrentAssets' => $this->otherNonCurrentAssets,
			'totalNonCurrentAssets' => $this->totalNonCurrentAssets,
			'otherAssets' => $this->otherAssets,
			'totalAssets' => $this->totalAssets,
			'totalPayables' => $this->totalPayables,
			'accountPayables' => $this->accountPayables,
			'otherPayables' => $this->otherPayables,
			'accruedExpenses' => $this->accruedExpenses,
			'shortTermDebt' => $this->shortTermDebt,
			'capitalLeaseObligationsCurrent' => $this->capitalLeaseObligationsCurrent,
			'taxPayables' => $this->taxPayables,
			'deferredRevenue' => $this->deferredRevenue,
			'otherCurrentLiabilities' => $this->otherCurrentLiabilities,
			'totalCurrentLiabilities' => $this->totalCurrentLiabilities,
			'longTermDebt' => $this->longTermDebt,
			'capitalLeaseObligationsNonCurrent' => $this->capitalLeaseObligationsNonCurrent,
			'deferredRevenueNonCurrent' => $this->deferredRevenueNonCurrent,
			'deferredTaxLiabilitiesNonCurrent' => $this->deferredTaxLiabilitiesNonCurrent,
			'otherNonCurrentLiabilities' => $this->otherNonCurrentLiabilities,
			'totalNonCurrentLiabilities' => $this->totalNonCurrentLiabilities,
			'otherLiabilities' => $this->otherLiabilities,
			'capitalLeaseObligations' => $this->capitalLeaseObligations,
			'totalLiabilities' => $this->totalLiabilities,
			'treasuryStock' => $this->treasuryStock,
			'preferredStock' => $this->preferredStock,
			'commonStock' => $this->commonStock,
			'retainedEarnings' => $this->retainedEarnings,
			'additionalPaidInCapital' => $this->additionalPaidInCapital,
			'accumulatedOtherComprehensiveIncomeLoss' => $this->accumulatedOtherComprehensiveIncomeLoss,
			'otherTotalStockholdersEquity' => $this->otherTotalStockholdersEquity,
			'totalStockholdersEquity' => $this->totalStockholdersEquity,
			'totalEquity' => $this->totalEquity,
			'minorityInterest' => $this->minorityInterest,
			'totalLiabilitiesAndTotalEquity' => $this->totalLiabilitiesAndTotalEquity,
			'totalInvestments' => $this->totalInvestments,
			'totalDebt' => $this->totalDebt,
			'netDebt' => $this->netDebt,
		];
	}

}