<?php declare(strict_types = 1);

namespace Shredio\FmpClient\Payload;

final readonly class RatiosTtm
{

	public function __construct(
		public string $symbol,
		public float|null $grossProfitMargin = null,
		public float|null $ebitMargin = null,
		public float|null $ebitdaMargin = null,
		public float|null $operatingProfitMargin = null,
		public float|null $pretaxProfitMargin = null,
		public float|null $continuousOperationsProfitMargin = null,
		public float|null $netProfitMargin = null,
		public float|null $bottomLineProfitMargin = null,
		public float|null $receivablesTurnover = null,
		public float|null $payablesTurnover = null,
		public float|null $inventoryTurnover = null,
		public float|null $fixedAssetTurnover = null,
		public float|null $assetTurnover = null,
		public float|null $currentRatio = null,
		public float|null $quickRatio = null,
		public float|null $solvencyRatio = null,
		public float|null $cashRatio = null,
		public float|null $priceToEarningsRatio = null,
		public float|null $priceToEarningsGrowthRatio = null,
		public float|null $forwardPriceToEarningsGrowthRatio = null,
		public float|null $priceToBookRatio = null,
		public float|null $priceToSalesRatio = null,
		public float|null $priceToFreeCashFlowRatio = null,
		public float|null $priceToOperatingCashFlowRatio = null,
		public float|null $debtToAssetsRatio = null,
		public float|null $debtToEquityRatio = null,
		public float|null $debtToCapitalRatio = null,
		public float|null $longTermDebtToCapitalRatio = null,
		public float|null $financialLeverageRatio = null,
		public float|null $workingCapitalTurnoverRatio = null,
		public float|null $operatingCashFlowRatio = null,
		public float|null $operatingCashFlowSalesRatio = null,
		public float|null $freeCashFlowOperatingCashFlowRatio = null,
		public float|null $debtServiceCoverageRatio = null,
		public float|null $interestCoverageRatio = null,
		public float|null $shortTermOperatingCashFlowCoverageRatio = null,
		public float|null $operatingCashFlowCoverageRatio = null,
		public float|null $capitalExpenditureCoverageRatio = null,
		public float|null $dividendPaidAndCapexCoverageRatio = null,
		public float|null $dividendPayoutRatio = null,
		public float|null $dividendYield = null,
		public int|null $enterpriseValue = null,
		public float|null $revenuePerShare = null,
		public float|null $netIncomePerShare = null,
		public float|null $interestDebtPerShare = null,
		public float|null $cashPerShare = null,
		public float|null $bookValuePerShare = null,
		public float|null $tangibleBookValuePerShare = null,
		public float|null $shareholdersEquityPerShare = null,
		public float|null $operatingCashFlowPerShare = null,
		public float|null $capexPerShare = null,
		public float|null $freeCashFlowPerShare = null,
		public float|null $netIncomePerEBT = null,
		public float|null $ebtPerEbit = null,
		public float|null $priceToFairValue = null,
		public float|null $debtToMarketCap = null,
		public float|null $effectiveTaxRate = null,
		public float|null $enterpriseValueMultiple = null,
	)
	{
	}

	/**
	 * @return array{symbol: string, grossProfitMargin: float|null, ebitMargin: float|null, ebitdaMargin: float|null, operatingProfitMargin: float|null, pretaxProfitMargin: float|null, continuousOperationsProfitMargin: float|null, netProfitMargin: float|null, bottomLineProfitMargin: float|null, receivablesTurnover: float|null, payablesTurnover: float|null, inventoryTurnover: float|null, fixedAssetTurnover: float|null, assetTurnover: float|null, currentRatio: float|null, quickRatio: float|null, solvencyRatio: float|null, cashRatio: float|null, priceToEarningsRatio: float|null, priceToEarningsGrowthRatio: float|null, forwardPriceToEarningsGrowthRatio: float|null, priceToBookRatio: float|null, priceToSalesRatio: float|null, priceToFreeCashFlowRatio: float|null, priceToOperatingCashFlowRatio: float|null, debtToAssetsRatio: float|null, debtToEquityRatio: float|null, debtToCapitalRatio: float|null, longTermDebtToCapitalRatio: float|null, financialLeverageRatio: float|null, workingCapitalTurnoverRatio: float|null, operatingCashFlowRatio: float|null, operatingCashFlowSalesRatio: float|null, freeCashFlowOperatingCashFlowRatio: float|null, debtServiceCoverageRatio: float|null, interestCoverageRatio: float|null, shortTermOperatingCashFlowCoverageRatio: float|null, operatingCashFlowCoverageRatio: float|null, capitalExpenditureCoverageRatio: float|null, dividendPaidAndCapexCoverageRatio: float|null, dividendPayoutRatio: float|null, dividendYield: float|null, enterpriseValue: int|null, revenuePerShare: float|null, netIncomePerShare: float|null, interestDebtPerShare: float|null, cashPerShare: float|null, bookValuePerShare: float|null, tangibleBookValuePerShare: float|null, shareholdersEquityPerShare: float|null, operatingCashFlowPerShare: float|null, capexPerShare: float|null, freeCashFlowPerShare: float|null, netIncomePerEBT: float|null, ebtPerEbit: float|null, priceToFairValue: float|null, debtToMarketCap: float|null, effectiveTaxRate: float|null, enterpriseValueMultiple: float|null}
	 */
	public function toArray(): array
	{
		return [
			'symbol' => $this->symbol,
			'grossProfitMargin' => $this->grossProfitMargin,
			'ebitMargin' => $this->ebitMargin,
			'ebitdaMargin' => $this->ebitdaMargin,
			'operatingProfitMargin' => $this->operatingProfitMargin,
			'pretaxProfitMargin' => $this->pretaxProfitMargin,
			'continuousOperationsProfitMargin' => $this->continuousOperationsProfitMargin,
			'netProfitMargin' => $this->netProfitMargin,
			'bottomLineProfitMargin' => $this->bottomLineProfitMargin,
			'receivablesTurnover' => $this->receivablesTurnover,
			'payablesTurnover' => $this->payablesTurnover,
			'inventoryTurnover' => $this->inventoryTurnover,
			'fixedAssetTurnover' => $this->fixedAssetTurnover,
			'assetTurnover' => $this->assetTurnover,
			'currentRatio' => $this->currentRatio,
			'quickRatio' => $this->quickRatio,
			'solvencyRatio' => $this->solvencyRatio,
			'cashRatio' => $this->cashRatio,
			'priceToEarningsRatio' => $this->priceToEarningsRatio,
			'priceToEarningsGrowthRatio' => $this->priceToEarningsGrowthRatio,
			'forwardPriceToEarningsGrowthRatio' => $this->forwardPriceToEarningsGrowthRatio,
			'priceToBookRatio' => $this->priceToBookRatio,
			'priceToSalesRatio' => $this->priceToSalesRatio,
			'priceToFreeCashFlowRatio' => $this->priceToFreeCashFlowRatio,
			'priceToOperatingCashFlowRatio' => $this->priceToOperatingCashFlowRatio,
			'debtToAssetsRatio' => $this->debtToAssetsRatio,
			'debtToEquityRatio' => $this->debtToEquityRatio,
			'debtToCapitalRatio' => $this->debtToCapitalRatio,
			'longTermDebtToCapitalRatio' => $this->longTermDebtToCapitalRatio,
			'financialLeverageRatio' => $this->financialLeverageRatio,
			'workingCapitalTurnoverRatio' => $this->workingCapitalTurnoverRatio,
			'operatingCashFlowRatio' => $this->operatingCashFlowRatio,
			'operatingCashFlowSalesRatio' => $this->operatingCashFlowSalesRatio,
			'freeCashFlowOperatingCashFlowRatio' => $this->freeCashFlowOperatingCashFlowRatio,
			'debtServiceCoverageRatio' => $this->debtServiceCoverageRatio,
			'interestCoverageRatio' => $this->interestCoverageRatio,
			'shortTermOperatingCashFlowCoverageRatio' => $this->shortTermOperatingCashFlowCoverageRatio,
			'operatingCashFlowCoverageRatio' => $this->operatingCashFlowCoverageRatio,
			'capitalExpenditureCoverageRatio' => $this->capitalExpenditureCoverageRatio,
			'dividendPaidAndCapexCoverageRatio' => $this->dividendPaidAndCapexCoverageRatio,
			'dividendPayoutRatio' => $this->dividendPayoutRatio,
			'dividendYield' => $this->dividendYield,
			'enterpriseValue' => $this->enterpriseValue,
			'revenuePerShare' => $this->revenuePerShare,
			'netIncomePerShare' => $this->netIncomePerShare,
			'interestDebtPerShare' => $this->interestDebtPerShare,
			'cashPerShare' => $this->cashPerShare,
			'bookValuePerShare' => $this->bookValuePerShare,
			'tangibleBookValuePerShare' => $this->tangibleBookValuePerShare,
			'shareholdersEquityPerShare' => $this->shareholdersEquityPerShare,
			'operatingCashFlowPerShare' => $this->operatingCashFlowPerShare,
			'capexPerShare' => $this->capexPerShare,
			'freeCashFlowPerShare' => $this->freeCashFlowPerShare,
			'netIncomePerEBT' => $this->netIncomePerEBT,
			'ebtPerEbit' => $this->ebtPerEbit,
			'priceToFairValue' => $this->priceToFairValue,
			'debtToMarketCap' => $this->debtToMarketCap,
			'effectiveTaxRate' => $this->effectiveTaxRate,
			'enterpriseValueMultiple' => $this->enterpriseValueMultiple,
		];
	}

}